Multiclass
NetherlandsForensicInstitute/lir-deprecated pull request #13
Opened 2020-06-30 08:11 UTC by wowtor

Alternative (limited) API for multiclass evaluation.

2020-06-30 09:26 UTC, rolfypma commented on lir/multiclass/calibration.py
> +    def __init__(self, backend):
hier verwacht ik een uitleg

2020-06-30 09:50 UTC, rolfypma commented on lir/multiclass/lr.py
> +class CalibratedScorer:
moeten we deze herhalen?

2020-06-30 11:03 UTC, rolfypma commented on lir/multiclass/metrics.py
> +    Calculates a log likelihood ratio cost (C_llr) for a series of likelihood ratios. The LRs must be formatted as
this is a weird condition, makes usage difficult, and the name 'lrs' somewhat misleading. There is no check on this currently

2020-06-30 11:04 UTC, rolfypma commented on lir/multiclass/calibration.py
> +    several distributions. Uses logistic regression for interpolation.
hoe werkt kalibratie uberhaupt voor multiclass? hebben we dat helder genoeg om de library uit te breiden?

2020-06-30 11:05 UTC, rolfypma requested changes
deze uitbreiding suggereert dat kalibratie voor multiclass een opgelost probleem is. Moeten we daar niet nog even over nadenken? Ook is het nu opgezet als hele aparte submodule, met dus veel dubbele code, vraag me af of dat wenselijk is

2020-06-30 13:02 UTC, TimoMatzen commented on lir/multiclass/metrics.py
> +    return np.exp(np.mean(np.log(values)))
Er is volgens mij geen noodzaak om dit zelf te implementeren: ``scipy.stats.mstats.gmean``

2020-06-30 14:29 UTC, wowtor commented on lir/multiclass/lr.py
> +class CalibratedScorer:
Ja tenminste deels, want de biclass versie neemt alleen de scores voor een van de klassen; we hebben ze allemaal nodig. Of we moeten de calibrator API aanpassen zodat die een multidimensional array accepteert.

2020-06-30 14:30 UTC, wowtor commented on lir/multiclass/metrics.py
> +    Calculates a log likelihood ratio cost (C_llr) for a series of likelihood ratios. The LRs must be formatted as
Suggestions?

2020-06-30 14:32 UTC, wowtor commented on lir/multiclass/calibration.py
> +    several distributions. Uses logistic regression for interpolation.
Volgens mij kunnen we het idee van kalibratie generaliseren naar meerdere klassen. Ik zou het graag toelichten :-)

2020-07-17 09:36 UTC, wowtor commented on lir/multiclass/calibration.py
> +    def __init__(self, backend):
done

2020-07-17 11:33 UTC, merged