Adds sample scores to NormalGenerator
NetherlandsForensicInstitute/lir-deprecated pull request #30
Opened 2021-05-18 15:24 UTC by TimoMatzen

Adds functionality to sample scores using the NormalGenerator.

2021-05-19 13:48 UTC, wowtor commented on lir/generators.py
> +        return odds / (1+odds), y if prob else odds, y
de `if` bindt sterker dan de `,`, niet waar?

2021-05-19 15:26 UTC, TimoMatzen commented on lir/generators.py
> +        return odds / (1+odds), y if prob else odds, y
Als in explicieter?

2021-05-28 08:04 UTC, wowtor commented on lir/generators.py
> +        return odds / (1+odds), y if prob else odds, y
Werkt de code? Deze zal waarschijnlijk een tuple van 3 teruggeven, maar ik denk dat 2 bedoeld is.

```
In [1]: 1, 2 if True else 3, 4                                                  
Out[1]: (1, 2, 4)

In [2]: (1, 2) if True else (3, 4)                                              
Out[2]: (1, 2)
````

2021-06-01 12:40 UTC, rolfypma-nfi commented on lir/generators.py
> +        return np.exp(-np.power(X - mu, 2) / (2 * sigma * sigma)) / np.sqrt(2 * np.pi * sigma * sigma)
zit dit niet standaard in numpy? Anders zit het zeker wel in scipy, mooier om dat te gebruiken

2021-06-01 12:40 UTC, rolfypma-nfi commented on lir/generators.py
> +        return odds / (1+odds), y if prob else odds, y
dit moet wel even opgelost!

- [ ]

2021-06-01 12:41 UTC, rolfypma-nfi requested changes
bug van wauter nog oplossen. overweeg om scipy te gebruiken

2021-06-01 13:09 UTC, TimoMatzen commented on lir/generators.py
> +        return odds / (1+odds), y if prob else odds, y
ik snap nu wat je bedoelde met de `if` bindt sterker, beter had je het eigenlijk niet kunnen beschrijven @wowtor . Had ik niet bij stilgestaan, maar is nu opgelost :)

2021-06-01 13:10 UTC, TimoMatzen commented on lir/generators.py
> +        return np.exp(-np.power(X - mu, 2) / (2 * sigma * sigma)) / np.sqrt(2 * np.pi * sigma * sigma)
zit standaard in scipy inderdaad, maar was hiervoor ook al zo dus had het zo gelaten, zag het niet als onderdeel van dit PR. Maar ik kan het nog toevoegen want ik ben het wel met je eens!

2021-07-09 17:43 UTC, wowtor approved these changes

2021-07-09 17:43 UTC, wowtor commented on lir/generators.py
> +        Sample scores in the form P(x|H1) for samples from the H2 distribution and the H1 distribution.
Niet `P(x|H1)` maar `P(H1)`. Het is eigenlijk een posterior probability bij gelijke priors.

2022-11-29 11:09 UTC, merged