Feature/specify ratio ss ds pairs
NetherlandsForensicInstitute/lir-deprecated pull request #59
Opened 2022-03-25 07:48 UTC by annajeannette

Option to specify ratio of ds/ss pairs in InstancePairing class. 

Naming: max_ratio, since it can become less when there are not enough ds pairs. 

If max_ratio is specified in combination with same_source_limit and/or different_source_limit, pairs are chosen such that all parameters are respected, while taking as much pairs as possible within these constraints.

2022-03-28 08:51 UTC, wowtor requested changes

2022-03-28 08:51 UTC, wowtor commented on lir/transformers.py
> +        Not that this transformer may cause performance problems with large datasets,
Not --> Note

2022-03-28 08:51 UTC, wowtor commented on lir/transformers.py
> +        if self._max_ratio and self._ds_limit == 'balanced':
De nieuwe parameter `max_ratio` maakt keyword `balanced` overbodig maar hij voegt wel complexiteit toe. Misschien is het dan mooier om deze te markeren als `deprecated` door deze uit de documentatie te verwijderen en, als dit keyword toch gegeven is, een deprecation warning te geven en `max_ratio` op 1 te zetten, en dan verder gaan met `max_ratio`.

2022-03-28 08:51 UTC, wowtor commented on lir/transformers.py
> +            self._ds_limit = n_ss_pairs * self._max_ratio
Deze overschrijft `self._ds_limit`, waardoor een volgende call naar `transform` andere resultaten zou kunnen opleveren. Zou deze limiet niet alleen binnen de call moeten gelden?

2022-03-28 08:51 UTC, wowtor commented on lir/transformers.py
> +            n_ss_pairs = min(x for x in [self._ss_limit, rows_same.size] if x is not None)
Deze regel is hetzelfde als regel 132 (en hierna wordt op regel 142 nog eens het aantal ss pairs bepaald)

2022-03-28 08:51 UTC, wowtor commented on tests/test_transformers.py
> +        max_ratio = 1_000
nice, underscore, die kende ik nog niet :)

2022-03-28 08:51 UTC, wowtor commented on lir/transformers.py
> +import warnings
ongebruikt?

2022-03-28 10:56 UTC, annajeannette commented on lir/transformers.py
> +        Not that this transformer may cause performance problems with large datasets,
aangepast

2022-03-28 11:00 UTC, annajeannette commented on lir/transformers.py
> +import warnings
Deze kan idd weg.

2022-03-28 14:36 UTC, annajeannette commented on lir/transformers.py
> +            self._ds_limit = n_ss_pairs * self._max_ratio
Aangepast, even alles herschreven ook zodat het een stuk korter is.

2022-03-28 14:36 UTC, annajeannette commented on lir/transformers.py
> +        if self._max_ratio and self._ds_limit == 'balanced':
Aangepast

2022-03-28 14:36 UTC, annajeannette commented on lir/transformers.py
> +            n_ss_pairs = min(x for x in [self._ss_limit, rows_same.size] if x is not None)
Weggehaald, hele stuk herschreven

2022-03-29 13:59 UTC, wowtor approved these changes
Ziet er goed uit!

2022-03-29 13:59 UTC, wowtor commented on lir/transformers.py
> +        if self._ds_limit == 'balanced':
Dit stukje zou al in de constructor kunnen staan want daar worden deze parameters gegeven

2022-03-31 08:55 UTC, annajeannette commented on lir/transformers.py
> +        if self._ds_limit == 'balanced':
Verplaatst.

2022-03-31 08:58 UTC, merged