percentile rank transformer works with multidimensional data
NetherlandsForensicInstitute/lir-deprecated pull request #75
Opened 2023-05-17 09:04 UTC by wowtor

The percentile rank transformer required a 2d matrix as input, i.e. each instance being represented by a 1d vector. This requirement is dropped in this PR. An instance can now be multidimensional. This is helpful if the input is not instances but pairs of instances.

2023-09-27 16:31 UTC, rolfypma-nfi requested changes
I'm not sure this works as intended but then again I don't grasp the details of what we expect the dimensions to be. An updated docstring will definitely help, tests would be awesome :P

2023-09-27 16:31 UTC, rolfypma-nfi commented on lir/transformers.py
> -        assert len(X.shape) == 2
docstring needs updating to reflect this change

2023-09-27 16:31 UTC, rolfypma-nfi commented on lir/transformers.py
> -        X = X.astype(float)
is this no longer an issue? would expect we still need this if we needed it before

2023-09-27 16:31 UTC, rolfypma-nfi commented on lir/transformers.py
> +        X = X.reshape(X.shape[0], -1)
if we naively put in a matrix of size (m, 2, f), this line would give a (m, 2 * f) size matrix and we would rank differently for the first-of-pair features and second-of-pair features. I assume that is not what we want? Do we expect features to now come first?

2023-09-27 16:31 UTC, rolfypma-nfi commented on lir/transformers.py
> +        X = X.reshape(X.shape[0], -1)
theoretically we could have a dataset at fit time that has a different ordering of dimensions than the one at transform time. Can/should we check for that? (do we expect one dimension to always have length 2 as this represents a pair?)

2023-09-28 12:43 UTC, wowtor commented on lir/transformers.py
> +        X = X.reshape(X.shape[0], -1)
If it is a trace-reference comparison this is actually what we want. If it is a trace-trace comparison this is not wrong but sub optimal and a better solution would be `reshape(-1, X.shape[1])`.

2023-09-29 07:32 UTC, wowtor commented on lir/transformers.py
> -        X = X.astype(float)
Not sure why we needed it before.

2023-10-09 08:06 UTC, wowtor commented on lir/transformers.py
> +        X = X.reshape(X.shape[0], -1)
We could check for it but it is primarily the responsibility of the user to feed legal input

2023-10-24 14:18 UTC, rolfypma-nfi commented on lir/transformers.py
> +        - `X` is a numpy array with one row per measurement
this has made it less clear. Why not
```suggestion
        - `X` is a numpy array with one row per measurement, eg dimension (n, f) or (n, f, 2) 
        with n = number of measurements, f = number of features. 
        
```

2023-10-24 14:21 UTC, rolfypma-nfi approved these changes

2023-10-24 14:21 UTC, rolfypma-nfi commented on lir/transformers.py
> +        X = X.reshape(X.shape[0], -1)
- [ ] add to the docstring that first-of-pair and second-of-pair are handled separately

2023-10-25 08:04 UTC, merged