made some sklearn utils
NetherlandsForensicInstitute/lir-deprecated pull request #8
Opened 2020-04-26 17:03 UTC by HHoofs

To smooth the process between sklearn and lir, I made some simple utils functions that map the `predict` to the `predict_lr` and vice-versa. I think of using the same name for convenience (e.g. the difference is purely based on the submodule, but maybe that is a bit to risky).

2020-04-27 11:11 UTC, TimoMatzen reviewed
> To smooth the process between sklearn and lir, I made some simple utils functions that map the `predict` to the `predict_lr` and vice-versa. I think of using the same name for convenience (e.g. the difference is purely based on the submodule, but maybe that is a bit to risky).

I think this pr is really what we need! I was first thinking about just changing the names in the lir api's to predict instead of predict_lr, however, I think this is a much cleaner solution. What do you mean by using the same name for convenience?

2020-04-27 11:11 UTC, TimoMatzen commented on lir/sk_utils.py
> +    In this way the `Pipeline` from sklearn, can be easily used in an lir based pipelnes
Klein dingetje maar in an lir based pipeline of in lir based pipelines ;)

2020-04-27 11:16 UTC, HHoofs commented
I could use the same name as the base class, but than it depends on the user if it selects the correct submodule

2020-04-27 11:27 UTC, HHoofs commented on lir/sk_utils.py
> +    In this way the `Pipeline` from sklearn, can be easily used in an lir based pipelnes
Zal ik fixen

2020-04-27 11:39 UTC, TimoMatzen commented
> I could use the same name as the base class, but than it depends on the user if it selects the correct submodule

A oke, I think I would keep the difference in names so it is clear for the user.

2020-04-27 11:40 UTC, TimoMatzen approved these changes

2020-04-28 13:18 UTC, wowtor commented
De conventie van sklearn is dat iedere classifier een `predict` heeft, en dat de return value een matrix is met waarden tussen 0 en 1 voor iedere klasse. Door deze functie te implementeren wek je de verwachting dat die ook hieraan voldoet. Dat is de reden dat hij `predict_lr` heet, en niet `predict`. Door `predict_lr` om te catten naar `predict` maak je het mogelijk om hem te gebruiken op plekken waar eigenlijk een classifier verwacht wordt, maar wil je dat eigenlijk wel, en kan dat geen onverwachte bijeffecten opleveren?

2020-04-28 13:36 UTC, HHoofs commented
> De conventie van sklearn is dat iedere classifier een `predict` heeft, en dat de return value een matrix is met waarden tussen 0 en 1 voor iedere klasse. Door deze functie te implementeren wek je de verwachting dat die ook hieraan voldoet. Dat is de reden dat hij `predict_lr` heet, en niet `predict`. Door `predict_lr` om te catten naar `predict` maak je het mogelijk om hem te gebruiken op plekken waar eigenlijk een classifier verwacht wordt, maar wil je dat eigenlijk wel, en kan dat geen onverwachte bijeffecten opleveren?

Dat zou onverwachte bijeffect kunnen opleveren, die zou ik kunnen documenteren. Probleem is nu dat het zich helemaal niet laat verwerken in een pipeline die het verder prima doet. Misschien een warning gooien (de eerste keer), en dat de rest de verantwoordelijkheid is van de gebruiker?

2020-04-28 13:57 UTC, rolfypma requested changes

2020-04-28 13:57 UTC, rolfypma commented on .github/workflows/pythonapp.yml
> +    - name: Test with unittest
waarom unittest, als wij eigenlijk altijd pytest gebruiken?

2020-04-28 13:57 UTC, rolfypma commented on lir/sk_utils.py
> +    def predict(self, X):
dit voelt als een megahack. predict verwacht geen lrs terug. waarom bouw je geen predict_proba in in de normale calibratedscorer, als de niet log odds versie van de LR? Dat is ook sklearn compatibel. predict kan ook, als lr>1. Als je het op deze manier wilt gebruiken zou ik dit schilletje in je eigen repo zetten, niet hier in de library

2020-04-28 14:10 UTC, HHoofs commented on .github/workflows/pythonapp.yml
> +    - name: Test with unittest
omdat er unittest in de code stond 🔄

2020-04-28 14:11 UTC, HHoofs commented
Ok ik heb het aangepast, ik heb nu alleen een Pipelineschilletje gemaakt

2020-04-28 14:11 UTC, HHoofs commented
Hierin kan je dan je CalibratedScorer stoppen en helemaal losgaan

2020-04-28 14:17 UTC, closed without merging

2020-05-13 14:09 UTC, wowtor commented on lir/sk_utils.py
> +    def predict(self, X):
Eens. `predict_proba` sluit beter aan bij sklearn conventies. Je kan LR omzetten naar probability met `lir.util.to_probability()`

2020-05-13 14:17 UTC, wowtor commented on .github/workflows/pythonapp.yml
> +    - name: Test with unittest
ik denk dat hij wel sneller wordt zonder pytest, en we gebruiken toch alleen maar unittest :-/