fixed bug in detection of pathological cases in devPAV
NetherlandsForensicInstitute/lir-deprecated pull request #92
Opened 2023-10-15 13:27 UTC by vergep

- made new detection of pathological cases
- created output for pathological cases
- adjusted tests

2023-10-23 15:38 UTC, wowtor requested changes
De tests gaan over `_devpavcalculator()`, maar die test niet de hele devpav. Daarvoor zijn `devpav()` en `devpav_estimated()`. Zouden we niet beter die testen in plaats van een deelfunctie?

2023-10-23 15:38 UTC, wowtor commented on tests/test_metrics.py
>          LRs = np.concatenate([LRssame, LRsdif])
Hier is een functie voor:
```py
LRs, y = Xn_to_Xy(LRssame, LRsdif)
```

2023-10-23 15:38 UTC, wowtor commented on tests/test_metrics.py
> +        pavlrs = cal.fit_transform(LRs, y)
Deze `pavlrs` wordt niet gebruikt. Kan dus weg, of beter nog, `PAVresult` kan weg. Geldt ook voor andere test cases.

2023-10-23 15:38 UTC, wowtor commented on tests/test_metrics.py
>          LRssame = (0, 1, 10**3)
Variabelennamen met hoofdletters zijn strijdig met conventie.

2023-10-23 15:38 UTC, wowtor commented on tests/test_metrics.py
> +        self.assertEqual(np.isnan(_devpavcalculator(LRs, PAVresult, y)), True)
```py
self.assertTrue(np.isnan(_devpavcalculator(LRs, PAVresult, y)))
```
Or, with description:
```py
self.assertTrue(np.isnan(_devpavcalculator(LRs, PAVresult, y)),
        "test on data where PAV-tranform has a horizontal line starting at log(X) = -Inf, and another one ending at log(X) = Inf")
```

2023-10-23 15:38 UTC, wowtor commented on tests/test_metrics.py
> +        print(pavlrs)
debug statement kan weg

2023-10-23 15:38 UTC, wowtor commented on lir/metrics.py
> +        return np.NINF
Devpav berekent toch de oppervlakte? Die kan niet negatief zijn.

2023-10-23 15:38 UTC, wowtor commented on lir/metrics.py
> +        return np.nan
Volgens een andere interpretatie (`metrics.py` regel 97) is dit niet `nan` maar `0`.

2023-10-23 15:38 UTC, wowtor commented on tests/test_metrics.py
> +        self.assertAlmostEqual(_devpavcalculator(LRs, PAVresult, y), np.inf)
Waarom `_devpavcalculator()` testen en niet `devpav()`?

2023-10-31 12:53 UTC, vergep commented on lir/metrics.py
> +        return np.nan
Since other interpretation will be removed, this comment is obsolete

2023-10-31 12:53 UTC, vergep commented on tests/test_metrics.py
> +        self.assertAlmostEqual(_devpavcalculator(LRs, PAVresult, y), np.inf)
Add an extra test for devpav()

2023-10-31 12:53 UTC, vergep commented on lir/metrics.py
> +        return np.NINF
This needs to be corrected!

2023-11-03 13:26 UTC, vergep commented on tests/test_metrics.py
>          LRs = np.concatenate([LRssame, LRsdif])
Check. Aangepast.

2023-11-03 13:27 UTC, vergep commented on tests/test_metrics.py
>          LRs = np.concatenate([LRssame, LRsdif])
Behalve dat het is: Xn_to_Xy(LRsdif, LRssame)

2023-11-03 13:27 UTC, vergep commented on tests/test_metrics.py
> +        pavlrs = cal.fit_transform(LRs, y)
Doorgevoerd

2023-11-03 13:27 UTC, vergep commented on tests/test_metrics.py
>          LRssame = (0, 1, 10**3)
Aangepast

2023-11-03 13:31 UTC, vergep commented on tests/test_metrics.py
> +        self.assertEqual(np.isnan(_devpavcalculator(LRs, PAVresult, y)), True)
Doorgevoerd

2023-11-03 13:31 UTC, vergep commented on tests/test_metrics.py
> +        print(pavlrs)
Doorgevoerd

2023-11-03 13:31 UTC, vergep commented on lir/metrics.py
> +        return np.NINF
Gecorrigeerd naar np.inf

2023-11-03 13:32 UTC, vergep commented on tests/test_metrics.py
> +        self.assertAlmostEqual(_devpavcalculator(LRs, PAVresult, y), np.inf)
Nu test ik ze allebei

2023-11-08 12:05 UTC, wowtor approved these changes
Nog een paar suggestions

2023-11-08 12:05 UTC, wowtor commented on lir/metrics.py
> +        # than it is not a  pathological case with weird X-values and devPAV can be calculated
```suggestion
        # then it is not a  pathological case with weird X-values and devPAV can be calculated
```

2023-11-08 12:05 UTC, wowtor commented on lir/metrics.py
> +def _calcsurface(c1, c2):
```suggestion
def _calcsurface(c1: (float, float), c2: (float, float)) -> float:
```

2023-11-08 12:05 UTC, wowtor commented on lir/metrics.py
>  def devpav(lrs, y):
```suggestion
def devpav(lrs: np.ndarray, y: np.ndarray) -> float:
```

2023-11-08 12:05 UTC, wowtor commented on setup.py
> +    install_requires=["matplotlib", "numpy", "scipy", "scikit-learn", "tqdm", "pandas"],
```suggestion
    install_requires=["matplotlib", "numpy", "scipy", "scikit-learn", "tqdm"],
```

2023-11-08 14:06 UTC, merged