Tlm
NetherlandsForensicInstitute/lir-deprecated pull request #94
Opened 2023-10-16 14:22 UTC by vergep

Merge TwoLevelModel with master.

Check at least the predict_proba function, since I wonder whether the output is in line with SKlearn classifiers?

2023-10-25 14:00 UTC, wowtor requested changes
- unit test faalt (afronding?)
- devpav moet eerst gemerged worden

2023-10-25 14:00 UTC, wowtor commented on lir/classifiers/two_level_model.py
> +def construct_3d_input(samples: Iterable[np.array]):
Deze is niet gedocumenteerd (en hoort waarschijnlijk niet in `classifiers.py`).

2023-10-25 14:00 UTC, wowtor commented on tests/test_two_level_model.py
> +        np.testing.assert_almost_equal(LRs_P / odds_R, ground_truth, decimal=10)
This test fails (seems to be rounding errors).

2023-10-25 14:00 UTC, wowtor commented on lir/classifiers/two_level_model.py
> +    def _get_n_features(X: np.ndarray, feature_ix: int = 2) -> int:
Hier heb ik een aantal functies static gemaakt, hernoemd van "fit" naar "get", en type hints toegevoegd

2023-10-25 14:00 UTC, wowtor commented on lir/classifiers/two_level_model.py
> +    def fit(self, X: np.ndarray, y: np.ndarray) -> "TwoLevelModelNormalKDE":
Misschien zouden we deze functie moeten hernoemen. Normaal verwacht je dat `fit()` dezelfde parameters accepteert als `transform()`. Dat is hier niet zo, met goede reden. Maar dan doet `fit()` dus niet direct wat je verwacht en dat kunnen we expliciet maken in naamgeving. Bijvoorbeeld `fit_background_population()` of zo. Ideeen?

2023-10-31 12:30 UTC, vergep commented on lir/classifiers/two_level_model.py
> +    def fit(self, X: np.ndarray, y: np.ndarray) -> "TwoLevelModelNormalKDE":
fit_on_unpaired_instances

2023-11-08 15:09 UTC, closed without merging